[package]
name = "particles"
version = "0.1.0"
authors = ["hperigo <hperigo@gmail.com>"]
edition = "2018"

[dependencies]
piralib = { path = "../../lib/piralib" }
rand = "*"
image = "0.20.1"

[build-dependencies]
gl_generator = "0.5.0"
