[package]
name = "piralib"
version = "0.1.0"
authors = ["hperigo <hperigo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "*"
nalgebra-glm = "*"
image = "*"

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
glutin = { version = "*" }

# [dependencies]
# imgui-glfw-rs = "*"
# gl_generator = "*"

[dev-dependencies]
rand = "*"
indextree = "*"